### ISSUE TITLE
Bicep build: is it possible to ignore Linter output that are 'Information level' 

### ISSUE THREAD

**Issue by Bhuard1** [piraces/azure-devops-bicep-task#14]
Hi,

I put in a linter file bicepconfig.json in my directory.

When I use the build task. In the build output I always see the following warning (so the build is indicated as partially succeeded).

##[warning]e:\b1\76\s\StorageAccount.bicep(1,1) : Info Bicep Linter Configuration: Custom bicepconfig.json file found (e:\b1\76\s\bicepconfig.json).

This is a 'information' level. 
Is there a way for the build to not report 'information' as a warning?

Thanks

**Comment by piraces** [comment]
Hi @Bhuard1 ,

I think this is a bug of this Azure DevOps tasks, I will investigate it and make it not to report `information` level as warning.
Sorry for the inconveniences.
I will solve this ASAP.

Thanks for the report.

**Comment by Bhuard1** [comment]
Hi, after reading the linter reference (https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-config) I found that putting verbose false, fixes the issue
"verbose: specify true to show the bicepconfig.json file used by Visual Studio Code.'

Sorry for any incovience.

**Comment by piraces** [comment]
No problem@Bhuard1 . Thanks for the information 👍
