### ISSUE TITLE
Latest version of bicep cli makes build task fail when using output directory

### ISSUE THREAD

**Issue by rickjansen-dev** [piraces/azure-devops-bicep-task#19]
There's a new version of the bicep cli released, the new version is 0.10.13

If using this devops task with output directory option set, it fails with this message:

```
##[error]The version '0.10.13' of Bicep CLI does not support an output directory or an output file as an option... Consider upgrading to a latest version of the Bicep CLI.
```

In the task there's some code to check if the bicep cli version is < 0.3. This fails because the cli version is parsed as a number/float.
See here: https://github.com/piraces/azure-devops-bicep-task/blob/38e8a196f2bd337ff411d6c56bc776b8ecec2849/src/run/index.ts#L91-L92
I suggest removing that piece of code altogether, or at least the parsing of the version number should be changed.
```
Number.parseFloat("0.10.13")
0.1
```

**Comment by piraces** [comment]
Ouch 😞 
Thanks for letting me know! I will fix this ASAP and release a new version in the marketplace.

**Comment by rickjansen-dev** [comment]
Thanks for fixing this :+1:
