### ISSUE TITLE
How do I pass parameters to my bicep file in Azure DevOps

### ISSUE THREAD

**Issue by kullen** [piraces/azure-devops-bicep-task#3]
So excited Bicep is available in DevOps now. 

I'm trying to mimic how my ARM template deployment works.  I have 1 template and I pass parameters to it based on the service I am deploying and environment I am deploying to.

screen shot of ARM Template Deployment from DevOp
![image](https://user-images.githubusercontent.com/10735864/110709744-4ff49680-81c2-11eb-8363-bcf147a49be9.png)

**Comment by piraces** [comment]
Hello,

Thanks for using the Azure DevOps extension! 😄 

At the time of writting this, Bicep CLI has no support for passing or overriding parameters, so the task of the Bicep extension will no offer it. But there is some work in progress by the Bicep team: https://github.com/Azure/bicep/issues/1278

If you want to mimic the ARM template deployment with a Bicep file, the process in the pipeline would be something as:
- Install the bicep CLI.
- Build the `.bicep` file.
- Deploy the ARM template with the same overrides you have initially.

To visualize this better, I have an example pipeline you could see here: https://dev.azure.com/raulejea/Bicep%20Tasks/_build?definitionId=20&_a=summary

![Example pipeline](https://user-images.githubusercontent.com/11027628/110966499-98908900-8355-11eb-92fe-08ea54ed1065.png)

As you can see, I'm replacing the `storageAccountType` as you do in your screenshot, and this parameter is defined in [my `.bicep` file here](https://github.com/piraces/azure-devops-bicep-task/blob/b9729d83f115a26c2ba99ea7c926b55b63130b7b/arm_templates/arm_storage_account.bicep#L9).

That bicep parameter would be converted to an ARM parameter by the `bicep build` command, so your process would be the same.

Hope this will solve your doubts!

Nevertheless, if you have any doubts about transitioning between ARM and Bicep, maybe the team at https://github.com/Azure/bicep could help answer this type of questions better.
